version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Josh-Cena
  - GeMini-220
  labels:
  - dependencies
  ignore:
  - dependency-name: remark-math
    versions:
    - ">= 4.a, < 5"
  commit-message:
    prefix: Dependencies
    include: scope
