packageExtensions:
  "@docusaurus/module-type-aliases@*":
    dependencies:
      "@docusaurus/react-loadable": ^5.5.2
      react-loadable: "npm:@docusaurus/react-loadable@^5.5.2"
  "@docusaurus/theme-classic@*":
    dependencies:
      utility-types: ^3.10.0
  "@docusaurus/theme-common@*":
    dependencies:
      history: ^4.9.0
  "@docusaurus/types@*":
    dependencies:
      history: ^4.9.0

yarnPath: .yarn/releases/yarn-3.6.3.cjs
