version: 2

jobs:

  build:
    docker:
      - image: circleci/node:16.4.2
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build Website
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - node_modules

  deploy-gh-pages:
    docker:
      - image: circleci/node:16.4.2
    steps:
      - checkout
      - run:
          name: Configure Git Credentials
          command: |
            git config --global user.email "computerizationbot@gmail.com"
            git config --global user.name "computerization-bot"
            echo "machine github.com login computerization-bot password $GITHUB_DOCUSAURUS_BOT" > ~/.netrc
      - attach_workspace:
          at: .
      - run:
          name: Deploy to GitHub Pages
          command: GIT_USER=computerization-bot yarn run deploy
          # Set environment variables so that project is deployed correctly
          environment:
            ORGANIZATION_NAME: Computerization
            PROJECT_NAME: computerization.github.io


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy-gh-pages:
          requires:
            - build
          filters:
            branches:
              only: master
